// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agentero/agentero.proto

package agentero

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestById struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestById) Reset()         { *m = RequestById{} }
func (m *RequestById) String() string { return proto.CompactTextString(m) }
func (*RequestById) ProtoMessage()    {}
func (*RequestById) Descriptor() ([]byte, []int) {
	return fileDescriptor_144dba805ca079d1, []int{0}
}

func (m *RequestById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestById.Unmarshal(m, b)
}
func (m *RequestById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestById.Marshal(b, m, deterministic)
}
func (m *RequestById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestById.Merge(m, src)
}
func (m *RequestById) XXX_Size() int {
	return xxx_messageInfo_RequestById.Size(m)
}
func (m *RequestById) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestById.DiscardUnknown(m)
}

var xxx_messageInfo_RequestById proto.InternalMessageInfo

func (m *RequestById) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RequestByMobileNumber struct {
	MobileNumber         string   `protobuf:"bytes,1,opt,name=mobileNumber,proto3" json:"mobileNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestByMobileNumber) Reset()         { *m = RequestByMobileNumber{} }
func (m *RequestByMobileNumber) String() string { return proto.CompactTextString(m) }
func (*RequestByMobileNumber) ProtoMessage()    {}
func (*RequestByMobileNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_144dba805ca079d1, []int{1}
}

func (m *RequestByMobileNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestByMobileNumber.Unmarshal(m, b)
}
func (m *RequestByMobileNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestByMobileNumber.Marshal(b, m, deterministic)
}
func (m *RequestByMobileNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestByMobileNumber.Merge(m, src)
}
func (m *RequestByMobileNumber) XXX_Size() int {
	return xxx_messageInfo_RequestByMobileNumber.Size(m)
}
func (m *RequestByMobileNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestByMobileNumber.DiscardUnknown(m)
}

var xxx_messageInfo_RequestByMobileNumber proto.InternalMessageInfo

func (m *RequestByMobileNumber) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

type Policy struct {
	Premium              float64  `protobuf:"fixed64,1,opt,name=Premium,proto3" json:"Premium,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_144dba805ca079d1, []int{2}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetPremium() float64 {
	if m != nil {
		return m.Premium
	}
	return 0
}

func (m *Policy) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ContactPoliciesReply struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	MobileNumber         string    `protobuf:"bytes,2,opt,name=MobileNumber,proto3" json:"MobileNumber,omitempty"`
	Policies             []*Policy `protobuf:"bytes,3,rep,name=Policies,proto3" json:"Policies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ContactPoliciesReply) Reset()         { *m = ContactPoliciesReply{} }
func (m *ContactPoliciesReply) String() string { return proto.CompactTextString(m) }
func (*ContactPoliciesReply) ProtoMessage()    {}
func (*ContactPoliciesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_144dba805ca079d1, []int{3}
}

func (m *ContactPoliciesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactPoliciesReply.Unmarshal(m, b)
}
func (m *ContactPoliciesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactPoliciesReply.Marshal(b, m, deterministic)
}
func (m *ContactPoliciesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactPoliciesReply.Merge(m, src)
}
func (m *ContactPoliciesReply) XXX_Size() int {
	return xxx_messageInfo_ContactPoliciesReply.Size(m)
}
func (m *ContactPoliciesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactPoliciesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ContactPoliciesReply proto.InternalMessageInfo

func (m *ContactPoliciesReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContactPoliciesReply) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

func (m *ContactPoliciesReply) GetPolicies() []*Policy {
	if m != nil {
		return m.Policies
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestById)(nil), "agentero.RequestById")
	proto.RegisterType((*RequestByMobileNumber)(nil), "agentero.RequestByMobileNumber")
	proto.RegisterType((*Policy)(nil), "agentero.Policy")
	proto.RegisterType((*ContactPoliciesReply)(nil), "agentero.ContactPoliciesReply")
}

func init() {
	proto.RegisterFile("agentero/agentero.proto", fileDescriptor_144dba805ca079d1)
}

var fileDescriptor_144dba805ca079d1 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x8d, 0x91, 0x58, 0xa7, 0x1e, 0x64, 0xb0, 0x1a, 0x3d, 0x68, 0x59, 0x14, 0x7a, 0x90,
	0x0a, 0x15, 0xbc, 0x78, 0x6a, 0x15, 0x24, 0x07, 0x4b, 0x58, 0xfa, 0x02, 0x49, 0x33, 0x48, 0x20,
	0xc9, 0xc6, 0xcd, 0xe6, 0xb0, 0xe0, 0xf3, 0xf9, 0x5c, 0xd2, 0x35, 0x9b, 0x3f, 0x50, 0xf0, 0x36,
	0xdf, 0xf0, 0x9b, 0x6f, 0xbe, 0x9d, 0x85, 0xcb, 0xe8, 0x93, 0x0a, 0x45, 0x52, 0x3c, 0xda, 0x62,
	0x5e, 0x4a, 0xa1, 0x04, 0x8e, 0xac, 0x66, 0xf7, 0x30, 0xe6, 0xf4, 0x55, 0x53, 0xa5, 0x56, 0x3a,
	0x48, 0xf0, 0x02, 0xbc, 0xba, 0x22, 0x19, 0x24, 0xbe, 0x33, 0x75, 0x66, 0x2e, 0x6f, 0x14, 0x7b,
	0x81, 0x49, 0x8b, 0x7d, 0x88, 0x38, 0xcd, 0x68, 0x5d, 0xe7, 0x31, 0x49, 0x64, 0x70, 0x9a, 0xf7,
	0xb4, 0x19, 0x3b, 0xe1, 0x83, 0x1e, 0x7b, 0x06, 0x2f, 0x14, 0x59, 0xba, 0xd5, 0xe8, 0xc3, 0x71,
	0x28, 0x29, 0x4f, 0xeb, 0xdc, 0x80, 0x0e, 0xb7, 0x12, 0x11, 0x8e, 0x36, 0xba, 0x24, 0xff, 0xd0,
	0xcc, 0x9b, 0x9a, 0x7d, 0xc3, 0xf9, 0xab, 0x28, 0x54, 0xb4, 0x55, 0x66, 0x3c, 0xa5, 0x8a, 0x53,
	0x99, 0xe9, 0x1d, 0xbb, 0x8e, 0x72, 0x6a, 0x76, 0x99, 0x7a, 0x97, 0xa3, 0x9f, 0xab, 0xf1, 0x19,
	0xf4, 0xf0, 0x01, 0x46, 0xd6, 0xc8, 0x77, 0xa7, 0xee, 0x6c, 0xbc, 0x38, 0x9b, 0xb7, 0x87, 0xf9,
	0x4b, 0xc8, 0x5b, 0x62, 0xf1, 0xe3, 0x80, 0xbb, 0x0c, 0x03, 0xdc, 0xc0, 0xd5, 0x3b, 0xa9, 0x26,
	0xc8, 0xb2, 0x48, 0x2c, 0xb0, 0xd2, 0xc1, 0x1b, 0x4e, 0x3a, 0x83, 0xde, 0x19, 0xaf, 0x6f, 0xba,
	0xf6, 0xbe, 0x17, 0xb0, 0x03, 0x4c, 0xe1, 0xae, 0x73, 0xad, 0x06, 0xb6, 0x83, 0xcc, 0xb7, 0x7b,
	0x16, 0xf4, 0x81, 0xff, 0x57, 0xc5, 0x9e, 0xf9, 0xf3, 0xa7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xaf, 0xb2, 0x95, 0x54, 0x0e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	// Returns a policy holder and its policies by userID
	GetContactAndPoliciesByID(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ContactPoliciesReply, error)
	// Returns a single policyholder and its policies by MobileNumber
	GetContactsAndPoliciesByMobileNumber(ctx context.Context, in *RequestByMobileNumber, opts ...grpc.CallOption) (*ContactPoliciesReply, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetContactAndPoliciesByID(ctx context.Context, in *RequestById, opts ...grpc.CallOption) (*ContactPoliciesReply, error) {
	out := new(ContactPoliciesReply)
	err := c.cc.Invoke(ctx, "/agentero.API/GetContactAndPoliciesByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetContactsAndPoliciesByMobileNumber(ctx context.Context, in *RequestByMobileNumber, opts ...grpc.CallOption) (*ContactPoliciesReply, error) {
	out := new(ContactPoliciesReply)
	err := c.cc.Invoke(ctx, "/agentero.API/GetContactsAndPoliciesByMobileNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	// Returns a policy holder and its policies by userID
	GetContactAndPoliciesByID(context.Context, *RequestById) (*ContactPoliciesReply, error)
	// Returns a single policyholder and its policies by MobileNumber
	GetContactsAndPoliciesByMobileNumber(context.Context, *RequestByMobileNumber) (*ContactPoliciesReply, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) GetContactAndPoliciesByID(ctx context.Context, req *RequestById) (*ContactPoliciesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactAndPoliciesByID not implemented")
}
func (*UnimplementedAPIServer) GetContactsAndPoliciesByMobileNumber(ctx context.Context, req *RequestByMobileNumber) (*ContactPoliciesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContactsAndPoliciesByMobileNumber not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_GetContactAndPoliciesByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetContactAndPoliciesByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentero.API/GetContactAndPoliciesByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetContactAndPoliciesByID(ctx, req.(*RequestById))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetContactsAndPoliciesByMobileNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestByMobileNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetContactsAndPoliciesByMobileNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agentero.API/GetContactsAndPoliciesByMobileNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetContactsAndPoliciesByMobileNumber(ctx, req.(*RequestByMobileNumber))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agentero.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContactAndPoliciesByID",
			Handler:    _API_GetContactAndPoliciesByID_Handler,
		},
		{
			MethodName: "GetContactsAndPoliciesByMobileNumber",
			Handler:    _API_GetContactsAndPoliciesByMobileNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agentero/agentero.proto",
}
